import type { MetadataRoute } from "next";

/**
 * PWA manifest so the app is installable to the phone home screen
 * (docs/devops-strategy.md §1 — installable responsive web app, no offline).
 * Colors match the retro palette in app/globals.css (--olive / --panel).
 * Icons are generated by scripts/gen-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Pokémon TCG Binder",
    short_name: "TCG Binder",
    description: "Routes each card to a binder and half, and tracks evolution line state.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#fbf2dd",
    theme_color: "#6d7b3c",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
